### ISSUE TITLE
Python test instructions for Windows machines

### ISSUE THREAD

**Issue by ngutn24** [TYPuzzler/TYPuzzler.github.io#2]
**Describe the bug**
The Python tests section in the developer guidelines instruct the developer to install Homebrew with a command. However, Homebrew is only supported on macOS and Linux. As a result, there are no Windows-specific instructions in the guidelines.

**To Reproduce**
1. On a Windows machine, in command prompt run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

**Expected behavior**
Homebrew would be installed and then I could follow the rest of the instructions exactly.

**Screenshots**
![image](https://user-images.githubusercontent.com/50428140/169715812-c5eb5c0f-89f1-4e6e-83c0-f1fb4abdbbc0.png)

**Device Information (Please complete the following information. Computers only -- phones and tablets are not supported):**
 - Windows 10

**Additional context**

**Comment by seungjchoi** [comment]
Instructions have changed
