### ISSUE TITLE
Same Puzzle Piece Awarded Each Time

### ISSUE THREAD

**Issue by DavidSRoy** [TYPuzzler/TYPuzzler.github.io#3]
**Describe the bug**
After typing out the text successfully, I was awarded a puzzle piece, but it was the same piece as the previous 2 attempts.

**To Reproduce**
1. Click Start Typing
2. Type the text and click next once complete
3. See your puzzle piece and repeat steps 1 and 2 a couple more times

**Expected behavior**
I was expecting a different puzzle piece so that the user can eventually complete the puzzle.

**Device Information (Please complete the following information. Computers only -- phones and tablets are not supported):**
 - OS: MacOS 12 (Monterey)
 - Browser: Safari

**Comment by marg33** [comment]
We fixed it, thanks!
